#!/bin/sh
#
# Start the network....
#
# sleep 1 is to let the hardware come up
# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
 	echo "Starting network..."
	sleep 1
	/sbin/ifup -a
	;;
  stop)
	printf "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

