#!/bin/sh
#
# Start the network....
#
# sleep 3 is to let the hardware come up
# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
 	echo "Starting network..."
	sleep 3
	if cat /sys/class/net/eth0/operstate | grep -q "up" ; then
		/sbin/ifup eth0
	fi
	if [ -e /sys/class/net/wlan0/address ]; then
		/sbin/ifup wlan0
	fi
	;;
  stop)
	printf "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

