#!/bin/ash

echo 600000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq
echo 600000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
echo "userspace" > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
echo 600000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_setspeed